# Generated by Django 4.2.1 on 2023-05-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',), 'verbose_name_plural': 'Student Name'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='batch_name',
        ),
    ]
